#!/usr/bin/env bash

main() {
  local DATA='{"script": "%s", "style": "%s", "version": "%s"}'
  local SCRIPT=$(npx browserify client/scripts/main.js | npx uglifyjs | sed 's/"/\\"/g')
  local STYLE=$(npx node-sass --output-style compressed client/styles/main.scss | sed 's/"/\\"/g')
  local VERSION=$(node -e 'require("./package").version' -p)

  printf "$DATA" "$SCRIPT" "$STYLE" "$VERSION" | npx mustache - client/templates/main.xslt > public/main.xslt
  return $?
}

. tasks/mixins/execute
