#!/usr/bin/env bash

. tasks/mixins/colors

CURSOR_HIDE='\033[?25l'
CURSOR_RESET='\033[999D'
CURSOR_SHOW='\033[?25h'
SPINNER_FRAMES=('⠋' '⠙' '⠹' '⠸' '⠼' '⠴' '⠦' '⠧' '⠇' '⠏')
SPINNER_INDEX=0
SYMBOL_DONE='✓'
SYMBOL_FAIL='✖'

FUNCTIONS=$(declare -F | cut -d ' ' -f 3 | grep main)
SPINNER_LENGTH=${#SPINNER_FRAMES[@]}
TASK_NAME=$(basename $0)
TASK_LOG="${TASK_NAME}.log"

abort() {
  [ -n "$SPINNER_PID" ] && kill $SPINNER_PID &> /dev/null
  echo -e $CURSOR_SHOW
  exit 0
}

execute() {
  terminal && trap abort SIGINT
  terminal && echo -en $CURSOR_HIDE

  for FUNCTION in $FUNCTIONS; do
    header

    if terminal; then
      spinner &
      SPINNER_PID=$!
    fi

    $FUNCTION &> $TASK_LOG
    EXIT_CODE=$?

    if terminal; then
      kill $SPINNER_PID &> /dev/null
      wait $SPINNER_PID &> /dev/null
    fi

    footer

    [ "$EXIT_CODE" != 0 ] && break
  done

  terminal && echo -en $CURSOR_SHOW
  exit $EXIT_CODE
}

footer() {
  terminal && echo -en $CURSOR_RESET

  if [ $EXIT_CODE == 0 ]; then
    terminal && echo -en $COLOR_GREEN
    terminal && echo -n $SYMBOL_DONE || echo $SYMBOL_DONE
    terminal && echo -e $COLOR_RESET
  else
    terminal && echo -en $COLOR_RED
    terminal && echo -n $SYMBOL_FAIL || echo $SYMBOL_FAIL
    terminal && echo -e $COLOR_RESET
    [ -r $TASK_LOG ] && cat $TASK_LOG
  fi

  [ -r $TASK_LOG ] && rm $TASK_LOG
}

header() {
  FUNCTION_NAME=${FUNCTION#main_}

  terminal && echo -n '  '
  echo -n "${TASK_NAME/_/ } "

  if [ "$FUNCTION_NAME" != 'main' ]; then
    echo -n "${FUNCTION_NAME/_/ } "
  fi
}

spinner() {
  while true; do
    let 'SPINNER_INDEX=++SPINNER_INDEX % SPINNER_LENGTH'
    echo -en "${CURSOR_RESET}${COLOR_YELLOW}${SPINNER_FRAMES[$SPINNER_INDEX]}${COLOR_RESET}"
    sleep 0.05
  done
}

terminal() {
  [ -t 1 ]
}

execute
